name:                hcpf
version:             0.1.0.0
github:              "dapine/hcpf"
license:             BSD3
author:              "David Pinheiro"
maintainer:          "davepinh@gmail.com"
copyright:           "2018 David Pinheiro"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hcpf#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hcpf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hcpf

tests:
  hcpf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hcpf
